AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 4096
    EphemeralStorage:
        Size: 10240
  Api:
    BinaryMediaTypes:
      - image/png
      - "*/*"

Resources:
  HarengusBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bot/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HarengusBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HarengusBotApi:
    Description: "API Gateway endpoint URL for Prod stage for HarengusBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HarengusBotFunction:
    Description: "HarengusBot Lambda Function ARN"
    Value: !GetAtt HarengusBotFunction.Arn
  HarengusBotFunctionIamRole:
    Description: "Implicit IAM Role created for HarengusBot function"
    Value: !GetAtt HarengusBotFunctionRole.Arn
